### ISSUE TITLE
HTTP 500 error from Hubspot when getting forms list in HubspotFormsService getForms()

### ISSUE THREAD

**Issue by pappgergely** [jordannbeattie/craftcms-hubspot-forms#2]
I have noticed that even with a correctly set up private app token the list of forms is empty.

After some inspection and tweaking I have found that the Hubspot API URL in HubspotFormsService:23 is incorrect, and results in the HTTP 500 response from Hubspot:
`$link = "https://api.hubapi.com/marketing/v3/forms?limit=100";`

If I change it to this, then the list of forms is retrieved corectly:
`$link = "https://api.hubapi.com/marketing/v3/forms";`

IDK if this was working earlier, but now it's definitely not working.
Can you please fix this?

**Comment by pappgergely** [comment]
I've opened a PR that you can accept: https://github.com/jordannbeattie/craftcms-hubspot-forms/pull/3

**Comment by jordannbeattie** [comment]
Hi @pappgergely 

Sorry for such a late response. 

Can you confirm if this is still an issue for you? Tested today on latest version of the plugin and it's working as expected.

![2024-06-20 23 16 42](https://github.com/jordannbeattie/craftcms-hubspot-forms/assets/6815944/ad0b8982-7d60-4bf8-8d4b-2a5ec41efac8)

If it's still an issue for you, can you please add your Craft version, plugin version and PHP version?

**Comment by jordannbeattie** [comment]
Solved in versions 4.1.0 and 5.1.0. This was an issue in the Hubspot API where some access tokens would receive a 500 error when requesting more forms than exist in the portal. The new limit field can be used to set to a number equal to or less than the total forms in the portal.

**Comment by pappgergely** [comment]
Hi @jordannbeattie,

It appears the issue is related to some Hubspot account specific factors. Unfortunately, the problem isn’t fully resolved yet. While we now have the ability to fine-tune the limit (thank you for that!), we’re still not receiving all the forms via the API. The client we are working with has over 50 forms, but the API is only returning 33.

Interestingly, when we switch to the Forms API v2 (https://legacydocs.hubspot.com/docs/methods/forms/v2/get_forms), all forms are correctly displayed. We discovered that the Forms API v3, currently used by the plugin, is still “under development” and “in beta,” as noted on the HubSpot page: https://developers.hubspot.com/docs/api/marketing/forms.

To address this, I’ve refactored the HubspotFormsService class to utilize the v2 API, including the necessary URL, format parsing, and pagination logic. Would you be interested in incorporating this into your plugin? If so, I’d be happy to share the working code to assist with the implementation. Alternatively, I can fork the repository and use the patched version for this client.

Thank you for your continued efforts.
